site_name: Williams Company OpenShift Day 2 Operations
site_url: https://github.com/OpenShiftDay2
edit_uri: ""
site_author: Don Bailey

# Repository

repo_name: dontbailey/OpenShiftDay2
repo_url: https://github.com/dontbailey/OpenShiftDay2

nav:
    - Home: index.md
    - Day 1:
          - Cluster Management: day1/cluster-management.md
          - Identity Provider: day1/config-identity-provider.md
          - LDAP Configuration: day1/ldap-configuration.md
          - Roles and Role Bindings: day1/roles-and-role-bindings.md
    - Day 2:
          - Roles and Role Bindings: day2/roles-and-role-bindings.md
          - Image Registry: day2/config-image-registry.md
          - Global Pull Secret: day2/update-global-pull-secret.md
    - References Material: 
           - Operating OpenShift: Operating-Openshift-Red-Hat-Developer-ebook.pdf
theme:
    name: material
    logo: images/williams_logo.png
    favicon: images/williams_logo.png
    palette:
        - scheme: default
          primary: 0079C1
          accent: c2c2c5
    font:
        text: Helvetica Roman
    features:
        - navigation.indexes
        - search
        - content.code.copy
        - content.tabs.link
        - content.tooltips
        - navigation.top
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.expand
        - navigation.prune
        - navigation.indexes
        - navigation.footer
        - toc.follow
        - search.suggest
        - search.share
plugins:
    - open-in-new-tab
markdown_extensions:
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: "@@@"
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - admonition
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
