site_name: Williams Company OpenShift Day 2 Operations
site_url: https://github.com/OpenShiftDay2
edit_uri: ""
site_author: Don Bailey

# Repository

repo_name: dontbailey/OpenShiftDay2
repo_url: https://github.com/dontbailey/OpenShiftDay2

nav:
    - Home: index.md
    - Day 1 - Management:
          - Cluster and User Management: day1-cluster-and-user-management.md
          - Adding Worker Nodes: day1-adding-worker-nodes.md
          - Identity Provider: config-identity-provider.md
          - LDAP Configuration: day1-ldap-configuration.md
          - Roles and Role Bindings: day1-roles-and-role-bindings.md
    - Day 2 - Configuration:
          - Roles and Role Bindings: day1-roles-and-role-bindings.md
          - Image Registry: config-image-registry.md
          - Global Pull Secret: update-global-pull-secret.md
    - References Material: OpenShift_day2.md
theme:
    name: material
    logo: images/williams_logo.png
    favicon: images/williams_logo.png
    palette:
        - scheme: default
          primary: 0079C1
          accent: c2c2c5
    font:
        text: Helvetica Roman
    features:
        - navigation.indexes
        - search
        - content.code.copy
        - content.tabs.link
        - navigation.top
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - navigation.expand
        - navigation.prune
        - navigation.indexes
        - navigation.footer
        - toc.follow
        - search.suggest
        - search.share
plugins:
    - open-in-new-tab
markdown_extensions:
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: "@@@"
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
