site_name: Red Hat OpenShift Day 2
site_url: https://github.com/OpenShiftDay2
edit_uri: ""
site_author: Don Bailey

# Repository

repo_name: dontbailey/OpenShiftDay2
repo_url: https://github.com/dontbailey/OpenShiftDay2

nav:
    - Home: index.md
    - OpenShift Day 2: OpenShift_day2.md
    - Configuration:
          - Identity Provider: config-identity-provider.md
          - Image Registry: config-image-registry.md
          - Global Pull Secret: update-global-pull-secret.md
theme:
    name: material
    logo: assets/images/favicon.png
    palette:
        - scheme: slate
    features:
        - navigation.indexes
plugins:
    - open-in-new-tab
markdown_extensions:
    - def_list
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: "@@@"
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tasklist:
          custom_checkbox: true
